
package br.edu.ifpb.pos.viajei.client.hotel.hotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HotelsService", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8084/viajei-hotel/HotelsService?wsdl")
public class HotelsService
    extends Service
{

    private final static URL HOTELSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSSERVICE_EXCEPTION;
    private final static QName HOTELSSERVICE_QNAME = new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "HotelsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/viajei-hotel/HotelsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSSERVICE_WSDL_LOCATION = url;
        HOTELSSERVICE_EXCEPTION = e;
    }

    public HotelsService() {
        super(__getWsdlLocation(), HOTELSSERVICE_QNAME);
    }

    public HotelsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Hotels
     */
    @WebEndpoint(name = "HotelsPort")
    public Hotels getHotelsPort() {
        return super.getPort(new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "HotelsPort"), Hotels.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hotels
     */
    @WebEndpoint(name = "HotelsPort")
    public Hotels getHotelsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "HotelsPort"), Hotels.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSSERVICE_EXCEPTION!= null) {
            throw HOTELSSERVICE_EXCEPTION;
        }
        return HOTELSSERVICE_WSDL_LOCATION;
    }

}
