
package br.edu.ifpb.pos.soap.viajei.client.hotel.room;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RoomsService", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", wsdlLocation = "http://hotels-web:8080/viajei-hotel/RoomsService?wsdl")
public class RoomsService
    extends Service
{

    private final static URL ROOMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROOMSSERVICE_EXCEPTION;
    private final static QName ROOMSSERVICE_QNAME = new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "RoomsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hotels-web:8080/viajei-hotel/RoomsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMSSERVICE_WSDL_LOCATION = url;
        ROOMSSERVICE_EXCEPTION = e;
    }

    public RoomsService() {
        super(__getWsdlLocation(), ROOMSSERVICE_QNAME);
    }

    public RoomsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Rooms
     */
    @WebEndpoint(name = "RoomsPort")
    public Rooms getRoomsPort() {
        return super.getPort(new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "RoomsPort"), Rooms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Rooms
     */
    @WebEndpoint(name = "RoomsPort")
    public Rooms getRoomsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", "RoomsPort"), Rooms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMSSERVICE_EXCEPTION!= null) {
            throw ROOMSSERVICE_EXCEPTION;
        }
        return ROOMSSERVICE_WSDL_LOCATION;
    }

}
