FROM postgres
MAINTAINER Pedro Arthur <pfernandesvasconcelos@gmail.com>
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 123456
ENV POSTGRES_DB viajei-hotel
COPY tables.sql /docker-entrypoint-initdb.d/