
package br.edu.ifpb.pos.viajei.client.ticket.transports;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Transports", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Transports {


    /**
     * 
     * @param newTransport
     */
    @WebMethod
    @RequestWrapper(localName = "addTransport", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.AddTransport")
    @ResponseWrapper(localName = "addTransportResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.AddTransportResponse")
    public void addTransport(
        @WebParam(name = "newTransport", targetNamespace = "")
        Transport newTransport);

    /**
     * 
     * @param transportId
     */
    @WebMethod
    @RequestWrapper(localName = "removeTransport", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.RemoveTransport")
    @ResponseWrapper(localName = "removeTransportResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.RemoveTransportResponse")
    public void removeTransport(
        @WebParam(name = "transportId", targetNamespace = "")
        Long transportId);

    /**
     * 
     * @param updatedTransport
     */
    @WebMethod
    @RequestWrapper(localName = "updateTransport", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.UpdateTransport")
    @ResponseWrapper(localName = "updateTransportResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.UpdateTransportResponse")
    public void updateTransport(
        @WebParam(name = "updatedTransport", targetNamespace = "")
        Transport updatedTransport);

    /**
     * 
     * @param transportId
     * @return
     *     returns br.edu.ifpb.pos.viajei.client.ticket.transports.Transport
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTransportById", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.FindTransportById")
    @ResponseWrapper(localName = "findTransportByIdResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.FindTransportByIdResponse")
    public Transport findTransportById(
        @WebParam(name = "transportId", targetNamespace = "")
        Long transportId);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.viajei.client.ticket.transports.Transport>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllTransports", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.ListAllTransports")
    @ResponseWrapper(localName = "listAllTransportsResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.transports.ListAllTransportsResponse")
    public List<Transport> listAllTransports();

}
