
package br.edu.ifpb.pos.soap.viajei.client.transports.routes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Routes", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Routes {


    /**
     * 
     * @param routeId
     * @return
     *     returns br.edu.ifpb.pos.soap.viajei.client.transports.routes.Route
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRouteById", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.transports.routes.FindRouteById")
    @ResponseWrapper(localName = "findRouteByIdResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.transports.routes.FindRouteByIdResponse")
    public Route findRouteById(
        @WebParam(name = "routeId", targetNamespace = "")
        Long routeId);

}
