version: "2"
services:
  db:
    container_name: viajei-agency-db
    image: viajei-agency-postgres
    build: ./database
    ports: 
      - "5437:5432"
    expose:
      - 5437
    volumes:
      - viajei-agency-postgres:/var/lib/postgresql/data
  web:
    container_name: viajei-agency-web
    build: .
    image: viajei-agency-payara
    ports:
      - "8086:8080"
    links: 
      - "db:viajei-agency-db"
    expose:
      - 8086
networks:
  default:
    external:
      name: viajei
volumes:
  viajei-agency-postgres:
    driver: local 
