
package br.edu.ifpb.pos.viajei.client.hotel.room;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Rooms", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Rooms {


    /**
     * 
     * @param roomId
     * @return
     *     returns br.edu.ifpb.pos.viajei.client.hotel.room.Room
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRoomById", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.FindRoomById")
    @ResponseWrapper(localName = "findRoomByIdResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.FindRoomByIdResponse")
    public Room findRoomById(
        @WebParam(name = "roomId", targetNamespace = "")
        Long roomId);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.viajei.client.hotel.room.Room>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllRooms", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.ListAllRooms")
    @ResponseWrapper(localName = "listAllRoomsResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.ListAllRoomsResponse")
    public List<Room> listAllRooms();

    /**
     * 
     * @param newRoom
     */
    @WebMethod
    @RequestWrapper(localName = "addRoom", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.AddRoom")
    @ResponseWrapper(localName = "addRoomResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.AddRoomResponse")
    public void addRoom(
        @WebParam(name = "newRoom", targetNamespace = "")
        Room newRoom);

    /**
     * 
     * @param updatedRoom
     */
    @WebMethod
    @RequestWrapper(localName = "updateRoom", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.UpdateRoom")
    @ResponseWrapper(localName = "updateRoomResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.UpdateRoomResponse")
    public void updateRoom(
        @WebParam(name = "updatedRoom", targetNamespace = "")
        Room updatedRoom);

    /**
     * 
     * @param roomId
     */
    @WebMethod
    @RequestWrapper(localName = "removeRoom", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.RemoveRoom")
    @ResponseWrapper(localName = "removeRoomResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.hotel.room.RemoveRoomResponse")
    public void removeRoom(
        @WebParam(name = "roomId", targetNamespace = "")
        Long roomId);

}
