version: "2"
services:
  db:
    container_name: viajei-hotel-db
    image: viajei-hotel-postgres
    build: ./database
    ports: 
      - "5435:5432"
    expose:
      - 5435
    volumes:
      - viajei-hotel-postgres:/var/lib/postgresql/data
  web:
    container_name: viajei-hotel-web
    build: .
    image: viajei-hotel-payara
    ports:
      - "8084:8080"
    links: 
      - "db:viajei-hotel-db"
    expose:
      - 8084
networks:
  default:
    external:
      name: viajei
volumes:
  viajei-hotel-postgres:
    driver: local 
