
package br.edu.ifpb.pos.soap.viajei.client.transports;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TransportsService", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", wsdlLocation = "http://transports-web:8080/viajei-transport/TransportsService?wsdl")
public class TransportsService
    extends Service
{

    private final static URL TRANSPORTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSPORTSSERVICE_EXCEPTION;
    private final static QName TRANSPORTSSERVICE_QNAME = new QName("http://ws.transport.viajei.soap.pos.ifpb.edu.br/", "TransportsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://transports-web:8080/viajei-transport/TransportsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSPORTSSERVICE_WSDL_LOCATION = url;
        TRANSPORTSSERVICE_EXCEPTION = e;
    }

    public TransportsService() {
        super(__getWsdlLocation(), TRANSPORTSSERVICE_QNAME);
    }

    public TransportsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Transports
     */
    @WebEndpoint(name = "TransportsPort")
    public Transports getTransportsPort() {
        return super.getPort(new QName("http://ws.transport.viajei.soap.pos.ifpb.edu.br/", "TransportsPort"), Transports.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transports
     */
    @WebEndpoint(name = "TransportsPort")
    public Transports getTransportsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.transport.viajei.soap.pos.ifpb.edu.br/", "TransportsPort"), Transports.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSPORTSSERVICE_EXCEPTION!= null) {
            throw TRANSPORTSSERVICE_EXCEPTION;
        }
        return TRANSPORTSSERVICE_WSDL_LOCATION;
    }

}
