
package br.edu.ifpb.pos.viajei.client.ticket.tickets;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TicketsService", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", wsdlLocation = "http://localhost:8083/viajei-ticket/TicketsService?wsdl")
public class TicketsService
    extends Service
{

    private final static URL TICKETSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TICKETSSERVICE_EXCEPTION;
    private final static QName TICKETSSERVICE_QNAME = new QName("http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", "TicketsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/viajei-ticket/TicketsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETSSERVICE_WSDL_LOCATION = url;
        TICKETSSERVICE_EXCEPTION = e;
    }

    public TicketsService() {
        super(__getWsdlLocation(), TICKETSSERVICE_QNAME);
    }

    public TicketsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns Tickets
     */
    @WebEndpoint(name = "TicketsPort")
    public Tickets getTicketsPort() {
        return super.getPort(new QName("http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", "TicketsPort"), Tickets.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tickets
     */
    @WebEndpoint(name = "TicketsPort")
    public Tickets getTicketsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", "TicketsPort"), Tickets.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETSSERVICE_EXCEPTION!= null) {
            throw TICKETSSERVICE_EXCEPTION;
        }
        return TICKETSSERVICE_WSDL_LOCATION;
    }

}
