
package br.edu.ifpb.pos.viajei.client.ticket.tickets;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Tickets", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tickets {


    /**
     * 
     * @param newTicket
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTicket", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.AddTicket")
    @ResponseWrapper(localName = "addTicketResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.AddTicketResponse")
    public Long addTicket(
        @WebParam(name = "newTicket", targetNamespace = "")
        Ticket newTicket);

    /**
     * 
     * @param updatedTicket
     */
    @WebMethod
    @RequestWrapper(localName = "updateTicket", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.UpdateTicket")
    @ResponseWrapper(localName = "updateTicketResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.UpdateTicketResponse")
    public void updateTicket(
        @WebParam(name = "updatedTicket", targetNamespace = "")
        Ticket updatedTicket);

    /**
     * 
     * @param ticketId
     */
    @WebMethod
    @RequestWrapper(localName = "removeTicket", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.RemoveTicket")
    @ResponseWrapper(localName = "removeTicketResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.RemoveTicketResponse")
    public void removeTicket(
        @WebParam(name = "ticketId", targetNamespace = "")
        Long ticketId);

    /**
     * 
     * @param ticketId
     * @return
     *     returns br.edu.ifpb.pos.viajei.client.ticket.tickets.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTicketById", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.FindTicketById")
    @ResponseWrapper(localName = "findTicketByIdResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.FindTicketByIdResponse")
    public Ticket findTicketById(
        @WebParam(name = "ticketId", targetNamespace = "")
        Long ticketId);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.viajei.client.ticket.tickets.Ticket>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllTickets", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.ListAllTickets")
    @ResponseWrapper(localName = "listAllTicketsResponse", targetNamespace = "http://ws.ticket.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.ticket.tickets.ListAllTicketsResponse")
    public List<Ticket> listAllTickets();

}
