
package br.edu.ifpb.pos.soap.viajei.client.hotel.bookings;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Bookings", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bookings {


    /**
     * 
     * @param bookingId
     */
    @WebMethod
    @RequestWrapper(localName = "removeBooking", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.RemoveBooking")
    @ResponseWrapper(localName = "removeBookingResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.RemoveBookingResponse")
    public void removeBooking(
        @WebParam(name = "bookingId", targetNamespace = "")
        Long bookingId);

    /**
     * 
     * @param bookingId
     * @return
     *     returns br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.Booking
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findBookingById", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.FindBookingById")
    @ResponseWrapper(localName = "findBookingByIdResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.FindBookingByIdResponse")
    public Booking findBookingById(
        @WebParam(name = "bookingId", targetNamespace = "")
        Long bookingId);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.Booking>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllBookings", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.ListAllBookings")
    @ResponseWrapper(localName = "listAllBookingsResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.ListAllBookingsResponse")
    public List<Booking> listAllBookings();

    /**
     * 
     * @param client
     * @param hotelId
     * @param daysQty
     * @param roomId
     * @param startDate
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "book", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.Book")
    @ResponseWrapper(localName = "bookResponse", targetNamespace = "http://ws.hotel.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.soap.viajei.client.hotel.bookings.BookResponse")
    public Long book(
        @WebParam(name = "hotelId", targetNamespace = "")
        Long hotelId,
        @WebParam(name = "roomId", targetNamespace = "")
        Long roomId,
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "startDate", targetNamespace = "")
        LocalDateTime startDate,
        @WebParam(name = "daysQty", targetNamespace = "")
        Integer daysQty);

}
