version: "2"
services:
  db:
    container_name: viajei-client-db
    image: viajei-client-postgres
    build: ./database
    ports: 
      - "5436:5432"
    expose:
      - 5436
    volumes:
      - viajei-client-postgres:/var/lib/postgresql/data
  web:
    container_name: viajei-client-web
    build: .
    image: viajei-client-payara
    ports:
      - "8085:8080"
    links: 
      - "db:viajei-client-db"
    expose:
      - 8085
networks:
  default:
    external:
      name: viajei
volumes:
  viajei-client-postgres:
    driver: local 
