
package br.edu.ifpb.pos.viajei.client.transports;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Transports", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Transports {


    /**
     * 
     * @param route
     * @param transportId
     */
    @WebMethod
    @RequestWrapper(localName = "addRoute", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.AddRoute")
    @ResponseWrapper(localName = "addRouteResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.AddRouteResponse")
    public void addRoute(
        @WebParam(name = "transportId", targetNamespace = "")
        Long transportId,
        @WebParam(name = "route", targetNamespace = "")
        Route route);

    /**
     * 
     * @param transport
     */
    @WebMethod
    @RequestWrapper(localName = "addTransport", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.AddTransport")
    @ResponseWrapper(localName = "addTransportResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.AddTransportResponse")
    public void addTransport(
        @WebParam(name = "transport", targetNamespace = "")
        Transport transport);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.viajei.client.transports.Transport>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllTransports", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.ListAllTransports")
    @ResponseWrapper(localName = "listAllTransportsResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.ListAllTransportsResponse")
    public List<Transport> listAllTransports();

    /**
     * 
     * @param cepFrom
     * @param transportType
     * @return
     *     returns java.util.List<br.edu.ifpb.pos.viajei.client.transports.Transport>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTransportsBy", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.SearchTransportsBy")
    @ResponseWrapper(localName = "searchTransportsByResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.SearchTransportsByResponse")
    public List<Transport> searchTransportsBy(
        @WebParam(name = "transportType", targetNamespace = "")
        TransportType transportType,
        @WebParam(name = "cepFrom", targetNamespace = "")
        String cepFrom);

    /**
     * 
     * @param transportId
     * @return
     *     returns br.edu.ifpb.pos.viajei.client.transports.Transport
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTransportById", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.FindTransportById")
    @ResponseWrapper(localName = "findTransportByIdResponse", targetNamespace = "http://ws.transport.viajei.soap.pos.ifpb.edu.br/", className = "br.edu.ifpb.pos.viajei.client.transports.FindTransportByIdResponse")
    public Transport findTransportById(
        @WebParam(name = "transportId", targetNamespace = "")
        Long transportId);

}
