version: "2"
services:
  db:
    container_name: viajei-transport-db
    image: viajei-transport-postgres
    build: ./database
    ports: 
      - "5433:5432"
    expose:
      - 5433
    volumes:
      - viajei-transport-postgres:/var/lib/postgresql/data
  web:
    container_name: viajei-transport-web
    build: .
    image: viajei-transport-payara
    ports:
      - "8082:8080"
    links: 
      - "db:viajei-transport-db"
    expose:
      - 8082
networks:
  default:
    external:
      name: viajei
volumes:
  viajei-transport-postgres:
    driver: local 
